[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
aaa123 = "dTsxz3p2zw6NrrkEQrxof4CK1hMqRQV94iiXQrDQWXC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/bigstar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
